const description = '从代码到通用智能，从独行到共创未来，未来已来，从 4AGI 开始！';

export default defineAppConfig({
  custom: {
    site: {
      name: '4AGI',
      description,
      ogImage: '/hero.png',
      ogImageComponent: 'FourAgi',
      ogImageColor: 'light',
      // umami: {
      //   enable: true,
      //   src: 'https://cloud.umami.is/script.js',
      //   dataWebsiteId: '',
      // },
    },
    theme: {
      customizable: true,
      color: 'violet',
      radius: 0.75,
    },
    banner: {
      enable: false,
      showClose: true,
      content: 'Welcome to **4AGI**',
      to: 'https://github.com/4agi-net/4agi',
      target: '_blank',
      border: true,
    },
    header: {
      title: '4AGI',
      showTitle: true,
      logo: {
        light: '/logo.svg',
        dark: '/logo-dark.svg',
      },
      darkModeToggle: true,
      nav: [{
        title: '探索',
        links: [{
          title: 'Prompt Engineering',
          to: '/docs/prompt-engineering/introduction',
          description: '提示词工程（Prompt Engineering）是您通往通用智能的必经之路',
          icon: 'lucide:box',
        }, {
          title: 'Cursor 从入门到精通',
          to: '/docs/cursor/about',
          description: '一款强大的 AI 编辑器，这将是一份您上手 Cursor 的最好教程',
          icon: 'vscode-icons:file-type-cursorrules',
        }, {
          title: 'Trae 从入门到实践',
          to: '/docs/trae/about',
          description: '国内出品的第一款桌面端 AI IDE，快来上手学习吧！',
          target: '_self',
          icon: '4agi:trae',
        }],
      }, {
        title: '社区',
        to: '/posts',
        target: '_self',
        showLinkIcon: false,
      }, {
        title: '资讯',
        to: '/information',
        target: '_self',
        showLinkIcon: false,
      }, {
        title: '导航',
        to: '/sites',
        target: '_self',
        showLinkIcon: false,
      }, {
        title: 'MCPs',
        to: '/mcps',
        target: '_self',
        showLinkIcon: false,
      }],
      links: [{
        icon: 'lucide:coffee',
        to: 'https://ko-fi.com/ztl_uwu',
        target: '_blank',
      }],
      githubButton: {
        enable: true,
        owner: 'isboyjc',
        repo: '4agi',
        showStarCount: true,
        target: '_blank',
        icon: 'lucide:github',
      },
    },
    aside: {
      useLevel: true,
      collapse: false,
      collapseLevel: 1,
      folderStyle: 'default',
    },
    main: {
      breadCrumb: true,
      showTitle: true,
      codeCopyToast: true,
      codeCopyIcon: 'lucide:copy',
      editLink: {
        enable: true,
        pattern: 'https://github.com/4agi-net/4agi/edit/main/content/:path',
        text: 'Edit this page',
        icon: 'lucide:square-pen',
        placement: ['docsFooter', 'toc'],
      },
      backToTop: true,
      codeIcon: {
        'package.json': 'vscode-icons:file-type-node',
        'tsconfig.json': 'vscode-icons:file-type-tsconfig',
        '.npmrc': 'vscode-icons:file-type-npm',
        '.editorconfig': 'vscode-icons:file-type-editorconfig',
        '.eslintrc': 'vscode-icons:file-type-eslint',
        '.eslintrc.cjs': 'vscode-icons:file-type-eslint',
        '.eslintignore': 'vscode-icons:file-type-eslint',
        'eslint.config.js': 'vscode-icons:file-type-eslint',
        'eslint.config.mjs': 'vscode-icons:file-type-eslint',
        'eslint.config.cjs': 'vscode-icons:file-type-eslint',
        '.gitignore': 'vscode-icons:file-type-git',
        'yarn.lock': 'vscode-icons:file-type-yarn',
        '.env': 'vscode-icons:file-type-dotenv',
        '.env.example': 'vscode-icons:file-type-dotenv',
        '.vscode/settings.json': 'vscode-icons:file-type-vscode',
        'nuxt': 'vscode-icons:file-type-nuxt',
        '.nuxtrc': 'vscode-icons:file-type-nuxt',
        '.nuxtignore': 'vscode-icons:file-type-nuxt',
        'nuxt.config.js': 'vscode-icons:file-type-nuxt',
        'nuxt.config.ts': 'vscode-icons:file-type-nuxt',
        'nuxt.schema.ts': 'vscode-icons:file-type-nuxt',
        'tailwind.config.js': 'vscode-icons:file-type-tailwind',
        'tailwind.config.ts': 'vscode-icons:file-type-tailwind',
        'vue': 'vscode-icons:file-type-vue',
        'ts': 'vscode-icons:file-type-typescript',
        'tsx': 'vscode-icons:file-type-typescript',
        'mjs': 'vscode-icons:file-type-js',
        'cjs': 'vscode-icons:file-type-js',
        'js': 'vscode-icons:file-type-js',
        'jsx': 'vscode-icons:file-type-js',
        'md': 'vscode-icons:file-type-markdown',
        'mdc': 'vscode-icons:file-type-markdown',
        'css': 'vscode-icons:file-type-css',
        'py': 'vscode-icons:file-type-python',
        'npm': 'vscode-icons:file-type-npm',
        'pnpm': 'vscode-icons:file-type-pnpm',
        'npx': 'vscode-icons:file-type-npm',
        'yarn': 'vscode-icons:file-type-yarn',
        'bun': 'vscode-icons:file-type-bun',
        'yml': 'vscode-icons:file-type-yaml',
        'json': 'vscode-icons:file-type-json',
        'terminal': 'lucide:terminal',
      },
    },
    footer: {
      copyright: '© 2024 4AGI. All rights reserved.',
      description,
      links: [{
        icon: 'lucide:github',
        to: 'https://github.com/4agi-net/4agi',
        target: '_blank',
      }, {
        icon: 'lucide:twitter',
        to: 'https://x.com/4agi',
        target: '_blank',
      }, {
        icon: 'lucide:heart',
        to: 'https://ko-fi.com/4agi',
        target: '_blank',
      }],
      linkGroups: [
        {
          title: '站点',
          links: [
            {
              title: '导航',
              to: '/sites',
              target: '_self',
            },
            {
              title: '资讯',
              to: '/information',
              target: '_self',
            },
            {
              title: '社区',
              to: '/posts',
              target: '_self',
            },
          ],
        },
        {
          title: '探索',
          links: [
            {
              title: 'Prompt',
              to: '/docs/prompt-engineering/introduction',
              target: '_self',
            },
            {
              title: 'Cursor',
              to: '/docs/cursor/about',
              target: '_self',
            },
            {
              title: 'Trae',
              to: '/docs/trae/about',
              target: '_self',
            },
          ],
        },
        {
          title: '团队',
          links: [
            {
              title: '关于我们',
              to: '/about',
              target: '_self',
            },
            {
              title: '联系我们',
              to: '/contact',
              target: '_self',
            },
          ],
        },
      ],
    },
    toc: {
      enable: true,
      enableInMobile: false,
      enableInHomepage: false,
      title: '目录',
      links: [{
        title: 'Star on GitHub',
        icon: 'lucide:star',
        to: 'https://github.com/4agi-net/4agi',
        target: '_blank',
        showLinkIcon: true,
      }, {
        title: 'Create Issues',
        icon: 'lucide:circle-dot',
        to: 'https://github.com/4agi-net/4agi/issues',
        target: '_blank',
        showLinkIcon: true,
      }],
      carbonAds: {
        enable: true,
        disableInDev: true,
        disableInMobile: false,
        fallback: false,
        fallbackMessage: 'Please support us by disabling your ad blocker.',
        code: '',
        placement: '4agi',
        format: 'cover',
      },
    },
    search: {
      enable: true,
      inAside: false,
    },
    data: {},
  },
});
